#!/usr/bin/env python3
"""The demos' stand-in for the edge, shared by all of them.

Every demo page needs the same thing and needs it for the same non-negotiable
reason: **the gateway and the storage service identify a project from the `Host`
header, and a browser is forbidden from setting `Host`.** It is a forbidden
header name, so no page can address a project directly however it is written.
Something in front has to supply it. In production that is Cloudflare and Caddy;
here it is this file.

Serving the page and the API from one origin also removes CORS from demos whose
subject is something else entirely — Phase 4's demo already earned the CORS
lesson the hard way (D-371), and repeating it in every later demo would teach
nothing new.

This module exists because the third demo was about to be the third copy. The
handler is deliberately narrow: named path prefixes, one fixed upstream, one
fixed Host. A dev tool that forwards arbitrary methods to an arbitrary host is an
open proxy, and these run on loopback next to a credentialed API.
"""
import os
import sys
import urllib.error
import urllib.request
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

# Everything a demo sends. Named rather than passed through, because the point of
# an allowlist is that adding to it is a decision.
COPY_REQUEST = ("apikey", "authorization", "content-type", "prefer", "accept",
                "range", "if-none-match", "x-upsert")
COPY_RESPONSE = ("content-type", "content-range", "content-disposition", "etag",
                 "cache-control", "x-request-id", "accept-ranges",
                 "x-content-type-options")


def project_ref(directory):
    """The ref the demo's script wrote into config.js — the one project served."""
    try:
        with open(os.path.join(directory, "config.js"), encoding="utf-8") as fh:
            for line in fh:
                if "ref:" in line:
                    return line.split("'")[1]
    except OSError:
        pass
    return None


def make_handler(prefixes, upstream, domain, directory):
    class Handler(SimpleHTTPRequestHandler):
        def do_GET(self):          # noqa: N802
            self.proxy("GET") if self.forwarded() else super().do_GET()

        def end_headers(self):
            # Never cache the demo's own files. `config.js` is regenerated by each
            # setup run and names a *specific* project, so a cached copy points at
            # a project that may no longer exist — which presents as "sign-in
            # failed (HTTP 401)" on a page whose API works perfectly when called
            # directly. That cost a debugging detour worth not repeating.
            if not self.forwarded():
                self.send_header("cache-control", "no-store")
            super().end_headers()

        def do_POST(self):         # noqa: N802
            self.proxy("POST") if self.forwarded() else self.send_error(405)

        def do_PUT(self):          # noqa: N802
            self.proxy("PUT") if self.forwarded() else self.send_error(405)

        def do_PATCH(self):        # noqa: N802
            self.proxy("PATCH") if self.forwarded() else self.send_error(405)

        def do_DELETE(self):       # noqa: N802
            self.proxy("DELETE") if self.forwarded() else self.send_error(405)

        def forwarded(self):
            return self.path.startswith(prefixes)

        def proxy(self, method):
            ref = project_ref(directory)
            if not ref:
                self.send_error(503, "no config.js — run this demo's setup script")
                return
            length = int(self.headers.get("content-length") or 0)
            # Read as bytes and forward as bytes, never decoded. A demo that
            # uploads an image is sending a PNG, and decoding it to text on the
            # way through would corrupt the upload for reasons no error message
            # would explain.
            body = self.rfile.read(length) if length else None
            req = urllib.request.Request(upstream + self.path, data=body, method=method)
            for h in COPY_REQUEST:
                v = self.headers.get(h)
                if v:
                    req.add_header(h, v)
            # The one header the browser could not have sent, and the reason this
            # file exists.
            req.add_header("Host", f"{ref}.{domain}")
            try:
                with urllib.request.urlopen(req, timeout=60) as res:
                    payload, status, headers = res.read(), res.status, res.headers
            except urllib.error.HTTPError as err:
                # A 4xx from the API is often the demo *working* — several steps
                # exist to produce one — so it is relayed verbatim rather than
                # turned into a proxy error that hides the code and the body.
                payload, status, headers = err.read(), err.code, err.headers
            except urllib.error.URLError as err:
                self.send_error(502, f"upstream {upstream} unreachable: {err.reason}")
                return
            self.send_response(status)
            for h in COPY_RESPONSE:
                v = headers.get(h)
                if v:
                    self.send_header(h, v)
            self.send_header("content-length", str(len(payload)))
            self.end_headers()
            if payload:
                self.wfile.write(payload)

        def log_message(self, fmt, *args):
            sys.stderr.write("  %s\n" % (fmt % args))

    return Handler


def serve(prefixes, port, directory=None):
    """Serve `directory` (default: the caller's cwd) with `prefixes` forwarded."""
    directory = directory or os.getcwd()
    upstream = os.environ.get("CB_DEMO_API", "http://127.0.0.1:8099")
    domain = os.environ.get("CB_PROJECT_DOMAIN", "localhost")
    handler = make_handler(tuple(prefixes), upstream, domain, directory)
    ThreadingHTTPServer(("127.0.0.1", port), handler).serve_forever()
